logging="INFO"
data-path="/opt/besu/data"
host-allowlist=[
"chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn",
"http://localhost:8280",
"http://localhost:8080",
"http://localhost:8014",
"https://explorer-testnet.anyrare.network",
"https://web-rc.anyrare.dev",
"https://web-dev.anyrare.dev",
"https://web-test.anyrare.dev",
"https://graphql-rc.anyrare.dev",
"https://graphql-dev.anyrare.dev",
"https://graphql-test.anyrare.dev"
]
node-private-key-file="/opt/besu/keys/key"
genesis-file="/opt/besu/genesis.json"
max-peers=64
# miner-enabled=true
min-gas-price=0

# rpc
rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-port=8545
rpc-http-cors-origins=[
"chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn",
"http://localhost:8280",
"http://localhost:8080",
"http://localhost:8014",
"https://explorer-testnet.anyrare.network",
"https://web-rc.anyrare.dev",
"https://web-dev.anyrare.dev",
"https://web-test.anyrare.dev",
"https://graphql-rc.anyrare.dev",
"https://graphql-dev.anyrare.dev",
"https://graphql-test.anyrare.dev"
]
rpc-http-api=["EEA","WEB3","ETH","NET","TRACE","DEBUG","ADMIN","IBFT"]

# ws
rpc-ws-enabled=true
rpc-ws-host="0.0.0.0"
rpc-ws-port=8546
rpc-ws-api=["EEA","WEB3","ETH","NET","TRACE","DEBUG","ADMIN","IBFT"]

# graphql
graphql-http-enabled=true
graphql-http-host="0.0.0.0"
graphql-http-port=8547
graphql-http-cors-origins=[
"chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn",
"http://localhost:8280",
"http://localhost:8080",
"http://localhost:8014",
"https://explorer-testnet.anyrare.network",
"https://web-rc.anyrare.dev",
"https://web-dev.anyrare.dev",
"https://web-test.anyrare.dev",
"https://graphql-rc.anyrare.dev",
"https://graphql-dev.anyrare.dev",
"https://grapqj-test.anyrare.dev"
]
    
# metrics
metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port=9545

# bootnodes
bootnodes=["enode://30db875f58437675186b88c64a921518f79a69f0ddd74336fff30da70fa809ad85a859632f86bcdd9baf3c6de3e5971f8c806970faaf862bfc1f61233576bdeb@172.16.236.30:30303"]

# static nodes
static-nodes-file="/config/static-nodes.json"
discovery-enabled=true
